test: prolog ml scala java rb php rb2 rb3 rb4 rb5 php3 php5
prolog:
	swipl tal0.pl
ml:
	ocaml tal0.ml
scala:
	scalac tal0.scala
	scala tal0
	rm *.class
java:
	javac tal0.java
	java tal0
	rm *.class
rb:
	ruby tal0.rb
php:
	php tal0.php
rb2:
	ruby tal0_2.rb
rb3:
	ruby tal0_3.rb
rb4:
	ruby tal0_4.rb
rb5:
	ruby tal0_5.rb
php3:
	php tal0_3.php
php5:
	php tal0_5.php
